### ISSUE TITLE
OPENTHREADS download hash mismatch

### ISSUE THREAD

**Issue by edgarriba** [orfeotoolbox/OTB#3]
While installing from source using superbuild got the following error

    checking whether make sets $(MAKE)... CMake Error at OPENTHREADS-stamp/download-OPENTHREADS.cmake:9 (file):
      file DOWNLOAD HASH mismatch

        for file: [/home/eriba/software/OTB/SuperBuild-archives/OpenSceneGraph-3.2.0.zip]
          expected hash: [4980f8692712a24d4c99f363f80c6814]
            actual hash: [d41d8cd98f00b204e9800998ecf8427e]

    make[2]: *** [OPENTHREADS/src/OPENTHREADS-stamp/OPENTHREADS-download] Error 1
    make[1]: *** [CMakeFiles/OPENTHREADS.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....

**Comment by grizonnetm** [comment]
Hi Edgar,

you're right, the URL has changed recently. The problem was reported on Mantis and fixed in branch release-5.0:

https://bugs.orfeo-toolbox.org/view.php?id=1077

To solve the issue on your side you can:

- if you-re compiling the last stable release 5.0 from a git clone, checkout and update the branch release-5.0

- If you're not using git clone, you can download a tarball which contains all sources for all dependencies and you set the path to the extracted archive in superbuild configuration using the DOWNLOAD_LOCATION cmake variable):

The archive is available here:

https://www.orfeo-toolbox.org/packages/SuperBuild-archives-5.0.tar.bz2

Regards,

**Comment by edgarriba** [comment]
@grizonnetm Simply solved that by modifying the hash by hand, only wanted to report that. Thanks anyway!
